# If you do not have OpenSSL installed, update
# the following line to use 'http://' instead
source 'https://rubygems.org'

gem 'slim', '>= 3.0'

# For faster file watcher updates on Windows:
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

# windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw, :x64_mingw]

# For better code snippets in markdown
gem 'middleman-vegas'

# Middleman Gems
gem 'middleman', '~>4.3.4'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-blog', '>= 4.0'
gem 'middleman-livereload'
gem 'middleman-minify-html'
gem 'middleman-sprockets', '~> 4.1.0'
gem 'middleman-syntax'
gem 'middleman-s3_sync'
gem 'mime-types'
gem 'nokogiri', '~> 1.8.2'
gem 'redcarpet', '~> 3.4.0'
gem 'rubocop', '~> 0.28.0', require: false
gem 'scss_lint', require: false
gem 'checker', require: false

group :development do
  gem 'pry'
end
